
project_id = "margqbeftjiulyaepxyy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.execute-sql]
verify_jwt = true

[functions.generate-solution]
verify_jwt = false

[functions.llm-proxy]
verify_jwt = false
