
project_id = "margqbeftjiulyaepxyy"

[api]
enabled = false
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = false
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false
port = 54324

[auth]
enabled = false
site_url = "http://localhost:3000"

[storage]
enabled = false

[realtime]
enabled = false

[analytics]
enabled = false
port = 54326

[vector]
enabled = false

[functions]
[functions.n8n-automation]
verify_jwt = true
