// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://margqbeftjiulyaepxyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hcmdxYmVmdGppdWx5YWVweHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mjk1NjMsImV4cCI6MjA2MjAwNTU2M30.RDngOOehDarDHXUYTfYp4npUoka6-altQ5fCn7M2I08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);